### ISSUE TITLE
Limited scope

### ISSUE THREAD

**Issue by branc116** [perrutquist/Zeros.jl#3]
This is awesome!

Can you pls make the same lib for number 1?

**Comment by perrutquist** [comment]
Thanks!

Good point about the number 1. Also, `Inf` and `NaN` should probably be useful as singular datatypes. Maybe the way forward would be to create a parametric datatype to represent any value, and make `Zero` a special case of this type.

**Comment by perrutquist** [comment]
There is now support for the number one in the "ones" branch. I'll still make a more general implementation when I get the time.

**Comment by branc116** [comment]
Good job! I'm happy with the implementation, just what I wanted!

Thank you!

You can close it now, if you want :)

**Comment by perrutquist** [comment]
Now, there is [StaticNumbers ](https://github.com/perrutquist/StaticNumbers.jl) which does much of what this package does, but for *any* number. StaticNumbers does not replace Zeros entirely, though, as it does not have all the methods (for functions like `sin`, `tan`, etc.) that pass `Zero()` (i.e. `StaticInteger{false}()) unchanged.
