### ISSUE TITLE
Interaction with Val(0)?

### ISSUE THREAD

**Issue by digital-carver** [perrutquist/Zeros.jl#4]
As of Julia 0.7, the Val types can be instantiated, so we can have `Val(0)` in a variable (previously we'd have had to deal with the type directly, since it wasn't instantiable). 

`Val` sounds like the answer to the "a parametric datatype to represent any value, and make Zero a special case of this type" aspiration mentioned in the other issue (#3). Except that, `Val{0}` isn't a subtype of `Real` or `Number` or anything, its supertype is just `Any` - so functions will have to deal with a variable having a `Val` value as a special case, and existing type assertions would prove even more restrictive than when using the current `Zero` from this module. 

Ideally, `Zero` would be a typedef on `Val{0}` except with a better place in the type hierarchy (which would be neat and simple). Barring that, this module should perhaps define `==(::Zero, ::Val{0}) = true`. 

Even better would be, if this module did something like `const Z = Union{Zero, Val{0}}` and then defined `+`, `*`, `>=`, etc. for this `Z` type (wherever the return value of the method is going to be the same for both `Zero` and `Val{0}`). That would make this module both provide a `Zero` type to users, make existing code that uses `Val(0)` more performant, and make interop between `Zero` and `Val{0}` quick and easy.

**Comment by perrutquist** [comment]
If the Zeros module would implement, say `Base.+(::Base.Val{0}, ::Base.Real)`, that would be [type piracy](https://docs.julialang.org/en/stable/manual/style-guide/#Avoid-type-piracy-1 ), which the style guide warns against. Hence, I'd rather create a new type.
