### ISSUE TITLE
Possible to add log and exp support?

### ISSUE THREAD

**Issue by oschulz** [perrutquist/Zeros.jl#6]
Would it be possible to add

```julia
Base.exp(::Zero) = One()
Base.log(::One) = Zero()
```

without causing unforseen trouble somewhere? If so, maybe

```julia
import Base.^
^(x::Number, ::Zero) = One()
^(x::Number, ::One) = x
Base.sqrt(::One) = One()
Base.sqrt(::Zero) = Zero()
```

as well?

**Comment by oschulz** [comment]
Ah, `^(x::Number, ::One)` would cause some ambiguous dispatch. Would need

```julia
import Base.^

^(x::Number, ::Zero) = One()
^(x::Float16, ::Zero) = One()
^(x::Float32, ::Zero) = One()
^(x::Float64, ::Zero) = One()
^(x::BigFloat, ::Zero) = One()
^(x::AbstractFloat, ::Zero) = One()

^(x::Number, ::One) = x
^(x::Float16, ::One) = x
^(x::Float32, ::One) = x
^(x::BigFloat, ::One) = x
^(x::AbstractFloat, ::One) = x
```

Would that be too much "fine-tuning" resp. too fragile?

It would make things like `A .^ Zero()` run in constant time, with zero-sized output. :-) Not sure that's a relevant use-case, though.

**Comment by perrutquist** [comment]
Done.

`^(x, p::One)` doesn't need special-casing, because those methods typically start with something like `p==1 && return x` anyway.  For example:
```
julia> @code_llvm 1.0^One()

;  @ math.jl:899 within `^'
define double @"julia_^_3800"(double) {
top:
;  @ math.jl:902 within `^'
  ret double %0
}
```

**Comment by oschulz** [comment]
Awesome, thanks!!
