### ISSUE TITLE
Common supertype for One and Zero?

### ISSUE THREAD

**Issue by oschulz** [perrutquist/Zeros.jl#7]
Would it make sense to have something like `One <: StaticBool <: Integer` and `Zero <: StaticBool <: Integer`, since Boolean algebra is a group?

**Comment by oschulz** [comment]
Ah, silly me, it's not a Boolean algebra, of course.

**Comment by perrutquist** [comment]
There is already an unexported `StaticBool`. 

```
julia> One <: Zeros.StaticBool <: Integer
true
```

**Comment by oschulz** [comment]
Oh, sorry, must have overlooked that. But in any case, it wouldn't really form a group, mathematically, since `One() + One()` is not a `One`. :-)
